version: "3.8"
services:
  app:
    build: ./.docker/php
    volumes:
      - ./src:/app

  web:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

  db:
    build: ./.docker/mysql
    tty: true
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  waf:
    build: ./.docker/modsecurity
    ports:
      - "8081:80"
    restart: always
    volumes:
      - ./.docker/modsecurity/log:/var/log/nginx

volumes:
  db-store:
